---

- name: baseline config for servers
  hosts: openstack_nodes
  gather_facts: no
  remote_user: root

  tasks:

  - name: create sources directory
    file: path=/etc/apt/sources.list.d state=directory

  - name: create file
    file: path=/etc/apt/sources.list.d/icehouse.list state=touch

  - name: add address for ubuntu cloud archive 
    lineinfile: dest=/etc/apt/sources.list.d/icehouse.list line="deb http://ubuntu-cloud.archive.canonical.com/ubuntu precise-updates/icehouse main"

  - name: install ubuntu cloud archive packages (+openstack recommended utils)
    apt: name={{ item }} state=present
    with_items: 
      - ubuntu-cloud-keyring
      - python-software-properties
      - software-properties-common
      - python-keyring

  - name: install apituide
    apt: name=aptitude state=present

  - name: apt-get update
    apt: update_cache=yes

  - name: apt-get upgrade
    apt: upgrade=full

  - name: apt-get dist-upgrade
    apt: upgrade=dist

  - name: install network utils
    apt: name={{ item }} state=present
    with_items: 
      - traceroute
      - vlan
      - ntp
      - bridge-utils

  - name: install text editors
    apt: name={{ item }} state=present
    with_items: 
      - vim
      - gedit

  - name: install kvm, libvirt, and utils
    apt: name={{ item }} state=present
    with_items: 
      - qemu-kvm
      - libvirt-bin
      - virt-manager


  - name: install xrdp
    apt: name=xrdp state=present

  - name: create admins group
    group: name=admins state=present 

  - name: create user to be used for rdp
    user: 
      name=netops
      group=admins
      password={{ pass1 }}
      shell=/bin/bash
      #password created with "mkpasswd --method=SHA-512" at bash prompt

  - name: modifying path for netops users.  required for commands such as 'ifconfig'
    lineinfile: dest=/home/{{ item }}/.bashrc line="export PATH=$PATH:/sbin"
    with_items:
      - netops
      #- jedelman

  - name: restart xrdp 
    service: name=xrdp state=restarted

